// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_ABOUT  1001
#define IDR_MNU_MAIN  2001
#define IDM_ABOUT  6001
#define IDM_OPEN  6002
#define IDR_ICO_MAIN  8001
#define IDR_SPIN_TIMER	4002
#define IDR_LABEL_TIMER  4010
#define IDR_SPIN_ROWS	4012
#define IDR_SPIN_COLS  4013
#define IDR_LABEL_ROWS  4015
#define IDR_LABEL_COLS  4016
#define IDR_EDIT1  4003
#define IDR_SPIN_MAXV  4018
#define IDR_LABEL_MAXV  4019
#define IDR_COLOR1  4006
#define IDR_COLOR2  4007
#define IDR_COLOR3  4008
#define IDM_STOP  6003
#define IDM_START  6004
#define IDM_STOP2  6005
